### PR TITLE
Add type annotations, add docstrings, replace `os` path strings by `pathlib`'s `Path` objects relative to globally configurable folder

### PR DESCRIPTION
**Pull request by bauwenst**
For my own understanding of the code and for better IDE support, I tried annotating all function parameters and return values with their static type. I also moved documentation from comments above the functions to docstrings inside the functions.

Paths were originally given as strings, but `Path` objects are much more convenient and common use. *All interfaces are backwards-compatible,* meaning you can still give strings where you are now expected to give a `Path` and those strings will be converted to a `Path` automatically.

There is now a function accessible to the user with `from sage_tokenizer import setSageFolder` which allows them to specify a folder *under which* the `results/` and `stats/` etc... are created. It defaults to the current working directory which is what happened originally.

### CODE REVIEW

**Comment by yuvalpinter** [comment]
Thank you! @bargazit can you verify backwards-compatibility in your testbed?

**Comment by bauwenst** [comment]
> Thank you! @bargazit can you verify backwards-compatibility in your testbed?

Speaking of which: is there a reason why it isn't included in this repo? I was looking for it so that I knew which functions were only backend and which were interacted with by existing code.

**Comment by bauwenst** [comment]
Oops, those commits are not supposed to go in this pull request. Brb doing some Git magic.

New PR lives at https://github.com/MeLeLBGU/SaGe/pull/12.

**Comment by bargazit** [comment]
> Thank you! @bargazit can you verify backwards-compatibility in your testbed?

Will do next week. I need to find what were the tests I ran previous time. It was mostly sanity checks as I wasn't suppose to change the code behavior only to re-organize it a bit (and that's the reason I didn't add these tests the first place)

**Pull request closed without merging**
